apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  uid: cb10d4b3-90d4-456c-8af2-c46366952ee0
  resourceVersion: '13018'
  creationTimestamp: '2023-11-05T11:44:26Z'
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.1.5
    helm.sh/chart: grafana-7.0.3
  annotations:
    meta.helm.sh/release-name: grafana
    meta.helm.sh/release-namespace: monitoring
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: v1
      time: '2023-11-05T11:44:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:grafana.ini: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
  selfLink: /api/v1/namespaces/monitoring/configmaps/grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = 'aksdemo.westeurope.cloudapp.azure.com'
    root_url = 'https://aksdemo.westeurope.cloudapp.azure.com/grafana'
    serve_from_sub_path = false


# https://github.com/grafana/grafana/issues/70110
