apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: dockersamples/examplevotingapp_vote
        ports:
        - name: vote
          containerPort: 80
        resources:
          requests:
            cpu: 20m
            memory: 500Mi
          limits:
            cpu: 40m
            memory: 500Mi
